/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Controller;
import Model.*;

/**
 *
 * @author K46
 */
public class ViewAtlit extends javax.swing.JFrame {

    /**
     * Creates new form ViewAtlit
     */
     Controller c = new Controller();
       public ViewAtlit() {
        initComponents();
        Invisible();
        Disable();
    
    }

      public void Invisible()
      {
         label_posisi.setVisible(false);
        label_kemenangan.setVisible(false);
        comboposisi.setVisible(false);
        spinnerkemenangan.setVisible(false);
        label_permainan.setVisible(false);
        combopermainan.setVisible(false);
        combopermainan.setVisible(false);
        comboposisi.setVisible(false);
        
      }
      public void Disable()
      {
          txtnama.setEnabled(false);
          txtumur.setEnabled(false);
          txtalamat.setEnabled(false);
          txthadiah.setEnabled(false);
          txtgaji.setEnabled(false);
          combotingkat.setEnabled(false);
         combopermainan.setEnabled(false);
         comboposisi.setEnabled(false);
         spinnerkemenangan.setEnabled(false);
      }
      public void Enable()
      {
         txtnama.setEnabled(true);
          txtumur.setEnabled(true);
          txtalamat.setEnabled(true);
          txthadiah.setEnabled(true);
          txtgaji.setEnabled(true);
          combotingkat.setEnabled(true); 
          combopermainan.setEnabled(true);
         comboposisi.setEnabled(true);
         spinnerkemenangan.setEnabled(true);
      }
      public void clear()
      {
          txtnama.setText("");
          txtumur.setText("");
          txtalamat.setText("");
          txthadiah.setText("");
          txtgaji.setText("");
          combotingkat.setSelectedItem("Pilih");
          combopermainan.setSelectedItem("Pilih");
          comboposisi.setSelectedItem("Pilih");
          spinnerkemenangan.setValue(0);
      }
      public void visible_bulutangkis()
      {
          ///bulu tangkis
          label_permainan.setVisible(true);
        combopermainan.setVisible(true);
        ///sepak bola
        
          label_posisi.setVisible(false);
        label_kemenangan.setVisible(false);
        comboposisi.setVisible(false);
        spinnerkemenangan.setVisible(false);
       
        comboposisi.setVisible(false);
      }
      public void visible_sepakbola()
      {
          ///bulu tangkis
          label_permainan.setVisible(false);
        combopermainan.setVisible(false);
        ///sepak bola
        
          label_posisi.setVisible(true);
        label_kemenangan.setVisible(true);
        comboposisi.setVisible(true);
        spinnerkemenangan.setVisible(true);
        comboposisi.setVisible((true));
      }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_permainan = new javax.swing.JLabel();
        label_posisi = new javax.swing.JLabel();
        label_kemenangan = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtumur = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        combotingkat = new javax.swing.JComboBox();
        txthadiah = new javax.swing.JTextField();
        txtgaji = new javax.swing.JTextField();
        combopermainan = new javax.swing.JComboBox();
        comboposisi = new javax.swing.JComboBox();
        spinnerkemenangan = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnbulutangkis = new javax.swing.JButton();
        btnbola = new javax.swing.JButton();
        btntampil = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tampilan Data Atlit");

        jLabel2.setText("Nama");

        jLabel3.setText("Umur");

        jLabel4.setText("Alamat");

        jLabel5.setText("Tingkat Pertandingan");

        jLabel6.setText("Hadiah");

        jLabel7.setText("Gaji Pokok");

        label_permainan.setText("Jenis Permainan");

        label_posisi.setText("Posisi");

        label_kemenangan.setText("Jumlah Kemenangan");

        txtumur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtumurKeyTyped(evt);
            }
        });

        combotingkat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih", "internasional", "nasional", "provinsi" }));

        txthadiah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthadiahKeyTyped(evt);
            }
        });

        txtgaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgajiKeyTyped(evt);
            }
        });

        combopermainan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih", "ganda", "single" }));

        comboposisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih", "gelandang", "penyerang", "kiper" }));

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Agensi Atlit Liu-Cong");

        btnbulutangkis.setText("Bulu Tangkis");
        btnbulutangkis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbulutangkisActionPerformed(evt);
            }
        });

        btnbola.setText("Sepak Bola");
        btnbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbolaActionPerformed(evt);
            }
        });

        btntampil.setText("Tampil");
        btntampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbulutangkis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntampil, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(label_permainan)
                                    .addComponent(label_posisi)
                                    .addComponent(label_kemenangan)
                                    .addComponent(btnbola, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtumur, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txthadiah)
                                                .addComponent(txtgaji)
                                                .addComponent(combopermainan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(comboposisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(spinnerkemenangan)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(combotingkat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 210, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(210, 210, 210)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(combotingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txthadiah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_permainan)
                            .addComponent(combopermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_posisi)
                            .addComponent(comboposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerkemenangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_kemenangan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbulutangkis)
                            .addComponent(btntampil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbatal)
                            .addComponent(btnbola))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbulutangkisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbulutangkisActionPerformed
                 // TODO add your handling code here:
                
               
                 visible_bulutangkis();
                 Enable();
                 
       //c.set_bulu_tangkis(txtnama.getText(), txtalamat.getText(), combotingkat.getSelectedItem().toString(),Double.parseDouble(txthadiah.getText()),combopermainan.getSelectedItem().toString(), Integer.parseInt(txtumur.getText()), Double.parseDouble(txtgaji.getText()));
        
        btnbola.setEnabled(false);
        btntampil.setEnabled(false);
        btnbulutangkis.setText("simpan");
    }//GEN-LAST:event_btnbulutangkisActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
         Disable();
         btnbulutangkis.setText("bulu tangkis");
         btnbola.setText("sepak bola");
         btnbola.setEnabled(true);
         btnbulutangkis.setEnabled(true);
         btntampil.setEnabled(true);
       
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbolaActionPerformed
        // TODO add your handling code here:
        visible_sepakbola();
        Enable();
        
        
      // c.set_sepak_bola(txtnama.getText(), txtalamat.getText(), combotingkat.getSelectedItem().toString(), comboposisi.getSelectedItem().toString(), Integer.parseInt(txtumur.getText()), Double.parseDouble(txtgaji.getText()), (spinnerkemenangan.getComponentCount()), Double.parseDouble(txthadiah.getText()));
          btnbola.setEnabled(false);
        btntampil.setEnabled(false);
        btnbulutangkis.setText("simpan");
        
        
    }//GEN-LAST:event_btnbolaActionPerformed

    private void txtumurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtumurKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtumurKeyTyped

    private void txthadiahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthadiahKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txthadiahKeyTyped

    private void txtgajiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgajiKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtgajiKeyTyped

    private void btntampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilActionPerformed
        // TODO add your handling code here:
        txtarea.setText(c.getbulutangkis());
        txtarea.setText(c.getsepakbola());
        
    }//GEN-LAST:event_btntampilActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        Enable();
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAtlit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnbola;
    private javax.swing.JButton btnbulutangkis;
    private javax.swing.JButton btntampil;
    private javax.swing.JComboBox combopermainan;
    private javax.swing.JComboBox comboposisi;
    private javax.swing.JComboBox combotingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_kemenangan;
    private javax.swing.JLabel label_permainan;
    private javax.swing.JLabel label_posisi;
    private javax.swing.JSpinner spinnerkemenangan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txthadiah;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
